### ISSUE TITLE
Only one application shown for default web browser

### ISSUE THREAD

**Issue by Letterus** [elementary/switchboard#215] opened 2021-08-14 21:09 UTC
## What Happened

I installed Firefox from AppCenter and set it as the default web browser. Later I wanted to change it back to "Web" (Epiphany). But the drop down menu only shows "Firefox"

## Expected Behavior
Display all browsers installed.

## Steps to Reproduce
1. Install Firefox using AppCenter
2. Set it as default
3. Try to change back to Web (Epiphany)

Maybe you need to restart/log in/out to reproduce that issue. I'm not sure. I'm stuck with "Firefox" currently. ;-)

### Logs

Where do I get them?

## Platform Information

elementary OS 6 Odin, updates installed.

**Comment by cassidyjames** [comment] 2021-08-16 17:28
Thanks for reporting! This looks like a duplicate of https://github.com/elementary/os/issues/412; please use the :+1: reaction on that issue to mark it as affecting you.

**Closed by cassidyjames** 2021-08-16 17:28 UTC
