### ISSUE TITLE
Integrate import/control of monitor colour profiles

### ISSUE THREAD

**Issue by dnisbetjones** [elementary/switchboard#225] opened 2022-01-03 01:48 UTC
### Problem

On elementaryOS 6.x, there is no way to calibrate one's display or import an .icc profile.

### Proposal

If you can integrate this into the display settings, that would allow users to set up calibrated displays on elementaryOS and do professional work that relies on accurate colour (or just have their monitors look nice).

**Comment by danirabbit** [comment] 2023-06-15 18:37
Closing as a duplicate of https://github.com/elementary/switchboard-plug-display/issues/5

**Closed by danirabbit** 2023-06-15 18:37 UTC
