### ISSUE TITLE
Wrong time from the internet

### ISSUE THREAD

**Issue by optimisme** [elementary/switchboard#217] opened 2021-09-06 05:46 UTC
## What Happened
If I set the config tool to get time automatically from the Internet, the region (Spain) is not properly detected and the time shows two hours less than the official one.

## Expected Behavior
The time of my location (Barcelona)

## Steps to Reproduce

1. Install elementary OS
2. Connect to the Internet
3. The time is wrong
4. Check the configuration to get the time from the Internet
5. The time is still wrong

## Platform Information
Up to date elementary OS6 (6 september 2021)

**Comment by marco4mp** [comment] 2022-04-06 03:15
HI. It looks like a duplicate of https://github.com/elementary/switchboard-plug-datetime/issues/96

**Comment by danrabbit** [comment] 2022-04-06 21:08
Closing as a duplicate of https://github.com/elementary/switchboard-plug-datetime/issues/96 thanks!

**Closed by danrabbit** 2022-04-06 21:08 UTC
