### ISSUE TITLE
Crash when opening Network plug

### ISSUE THREAD

**Issue by kicsyromy** [elementary/switchboard#213] opened 2021-08-05 06:12 UTC
## What Happened
Opening Network plug from Switchboard or from the network indicator crashes Switchboard

## Expected Behavior
Switchboard should not crash

## Steps to Reproduce
Open the Network plug from Switchboard

### Logs
```
(io.elementary.switchboard:20400): Gtk-CRITICAL **: 09:05:32.558: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
**
Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))
Bail out! Gtk:ERROR:../../../../gtk/gtkwidget.c:12412:gtk_widget_real_map: assertion failed: (_gtk_widget_get_realized (widget))

Thread 1 "io.elementary.s" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

## Platform Information

```
OS: elementary OS 6 Odin x86_64 (RC ISO compiled from os repository)
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.11.0-25-generic 
Uptime: 12 mins 
Packages: 2484 (dpkg), 29 (flatpak) 
Shell: zsh 5.8 
Resolution: 2560x1440, 2560x1440 
DE: Pantheon 
WM: Mutter(Gala) 
CPU: Intel i7-8650U (8) @ 4.200GHz 
GPU: Intel UHD Graphics 620 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 3041MiB / 15757MiB 
```
Output from ```ip addr```:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 8c:16:45:8a:49:a5 brd ff:ff:ff:ff:ff:ff
3: wlp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 38:de:ad:dc:a5:f0 brd ff:ff:ff:ff:ff:ff
4: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 0e:95:1b:bc:f4:81 brd ff:ff:ff:ff:ff:ff
5: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:d4:97:ca brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
6: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:d4:97:ca brd ff:ff:ff:ff:ff:ff
7: enx00e04c680034: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:e0:4c:68:00:34 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.48/24 brd 192.168.0.255 scope global dynamic noprefixroute enx00e04c680034
       valid_lft 505sec preferred_lft 505sec
    inet6 fe80::4e8c:62cc:9d54:6da2/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by kicsyromy** [comment] 2021-08-05 06:15
[core_dump.tar.gz](https://github.com/elementary/switchboard/files/6936312/core_dump.tar.gz)

**Comment by 413Michele** [comment] 2021-08-11 13:54
Affects me as well on the stable release, with an identical terminal message

## Platform Information

```
elementary OS 6 stable ISO with the latest updates
Intel Core i5-4300U
```

**Comment by danrabbit** [comment] 2021-08-11 17:35
Thanks for your report! This seems like a duplicate of https://github.com/elementary/switchboard-plug-network/issues/294

closing as duplicate

**Closed by danrabbit** 2021-08-11 17:35 UTC
