### ISSUE TITLE
Title bar or Menu Bar Dark Issue

### ISSUE THREAD

**Issue by rahidulislam** [elementary/switchboard#255] opened 2023-02-01 13:20 UTC
### What Happened?

When we switch dark theme, third party app like Telegram, Pycharm Professional Edition Title bar are not dark.

### Steps to Reproduce

1. settings
2. Desktop
3. Appearance
4. Dark Mode

### Expected Behavior

Dark Mode in Title bar of Third Party Apps like Telegram, Pycharm Professional Editions

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-02-01 14:51
Closing as duplicate of elementary/gala#956

**Closed by lenemter** 2023-02-01 14:51 UTC
