### ISSUE TITLE
Opening a switchboard plug directly from the main menu activates GTK search bar, which hijacks typed-in text

### ISSUE THREAD

**Issue by remalhaut** [elementary/switchboard#206] opened 2021-05-05 21:02 UTC
## What Happened
When a switchboard plug (e.g. Keyboard Shortcuts) is opened from the main menu, the GTK search bar is active. When attempting to type into dialog boxes (e.g. to create a keyboard shortcut), the typing is hijacked by the search bar (this may vary with keyboard layout - e.g. for me the "hijack" happened with a UK layout, but not US layout). 

## Expected Behavior
The search bar should be greyed out in each switchboard plug, as it is when a plug is activated from the main switchboard window.

## Steps to Reproduce

1. Open main menu. Search for a switchboard plug (e.g. Keyboard) and select it from the Settings section.
2. Plug window opens with search bar activated.

## Platform Information
Elementary OS 6 beta, kernel 5.8.0-50-generic
switchboard `2.4.0~r1096+pkg73~daily~ubuntu6.1`

**Comment by ryonakano** [comment] 2021-05-06 00:53
Thank you for your reporting, but closing as a duplicate of #194.

**Closed by ryonakano** 2021-05-06 00:53 UTC
