### ISSUE TITLE
artifacts in background for short time after suspend, and forever for "switch workspace"

### ISSUE THREAD

**Issue by amaroc** [elementary/switchboard#67] opened 2018-05-15 01:09 UTC
Reproduce: make suspend system (Power\Suspend). Go back, by push some keys.
Problem: background in artifacts for a short time. But Background in switch workspace still in artifacts forever (need restart to fix it).

lshw https://pastebin.com/Kj8QXTgf
dmidecode https://pastebin.com/KeDxnr0r

![screenshot from 2018-05-15 03 59 33](https://user-images.githubusercontent.com/4218383/40030821-5d64c78a-57f5-11e8-89fa-565e1a85d65c.png)

PS: Guys! I am so sorry about post here, i just dont know where i can give this feedback i look where it can be here on github but there too much "projects" in Elementary OS. So please move it to right place.

**Comment by cassidyjames** [comment] 2018-11-27 16:41
Thanks for reporting! It looks like this is actually a duplicate of https://github.com/elementary/gala/issues/21, which has been fixed in master.

**Closed by cassidyjames** 2018-11-27 16:41 UTC
