### ISSUE TITLE
No UI for assigning profile to a display

### ISSUE THREAD

**Issue by brownphotographic** [elementary/switchboard#185] opened 2020-08-18 12:32 UTC
**Problem**
ElementaryOS is missing a UI element to assign a profile to a display. Like other distros (e.g. Zorin), I expect to see it under Settings >> Displays and then under a display, choose an ICC profile.

**Use Case**
The use case for me is that as a photographer, I need to be able to have a calibrated display and choose between one or more ICC profiles (which I can create externally via DisplayCal, or on my Mac) and assign to the display device. 

**Workaround**
Currently I have to do it via DisplayCal. Would be nice to just have an option in the OS to do this.

**Comment by danrabbit** [comment] 2020-08-18 19:21
Closing as a duplicate of https://github.com/elementary/switchboard-plug-display/issues/5

**Closed by danrabbit** 2020-08-18 19:21 UTC

**Comment by brownphotographic** [comment] 2020-08-19 00:34
Thanks for the review of this
